apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: qc-api-state
  namespace: {{ include "queen-califia.ns" . }}
  labels:
{{ include "queen-califia.labels" . | indent 4 }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
